plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/rhys/Desktop/Appear CMO site/.claude/worktrees/stoic-nobel-afeb5d/BR-lead-gen/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/rhys/Desktop/Appear CMO site/.claude/worktrees/stoic-nobel-afeb5d/BR-lead-gen"
command = "astro build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]